// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP0ucnnIDWQUvnb8fPfz5GuKqpgBTcePA',
    appId: '1:758985702723:web:60e7326cd88602ed2803f6',
    messagingSenderId: '758985702723',
    projectId: 'cmsc23-todo-app-kltayawa',
    authDomain: 'cmsc23-todo-app-kltayawa.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-kltayawa.appspot.com',
    measurementId: 'G-D8R47F5PHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsBJHJwPQxKwc7FjSBMu7IXGMpcAJR8hc',
    appId: '1:758985702723:android:57428fe62ca9754c2803f6',
    messagingSenderId: '758985702723',
    projectId: 'cmsc23-todo-app-kltayawa',
    storageBucket: 'cmsc23-todo-app-kltayawa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdZoKLOmJZXGlAfAnD_S6iD1qkcVnTN_s',
    appId: '1:758985702723:ios:392a81034979ea942803f6',
    messagingSenderId: '758985702723',
    projectId: 'cmsc23-todo-app-kltayawa',
    storageBucket: 'cmsc23-todo-app-kltayawa.appspot.com',
    iosBundleId: 'com.example.week9Authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdZoKLOmJZXGlAfAnD_S6iD1qkcVnTN_s',
    appId: '1:758985702723:ios:392a81034979ea942803f6',
    messagingSenderId: '758985702723',
    projectId: 'cmsc23-todo-app-kltayawa',
    storageBucket: 'cmsc23-todo-app-kltayawa.appspot.com',
    iosBundleId: 'com.example.week9Authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP0ucnnIDWQUvnb8fPfz5GuKqpgBTcePA',
    appId: '1:758985702723:web:e432a39ad15e5df52803f6',
    messagingSenderId: '758985702723',
    projectId: 'cmsc23-todo-app-kltayawa',
    authDomain: 'cmsc23-todo-app-kltayawa.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-kltayawa.appspot.com',
    measurementId: 'G-JRXLBW0734',
  );

}